### ISSUE TITLE
Broken with latest Prism

### ISSUE THREAD

**Issue by carbontwelve** [Golmote/prism-treeview#1]
I stumbled across this prism plugin while searching for something that did the following:
![image](https://cloud.githubusercontent.com/assets/464699/24157920/b3e38f8a-0e52-11e7-9478-a85151a72049.png)

That screen grab is taken from here https://docs.statamic.com/installing#installing; having looked at their obfuscated source code, it looks like it does very similar behavior to this plugin, even using identical regex.

It is a shame that this two year old codebase is now broken.

**Comment by Golmote** [comment]
As far as I can tell, it still works: http://codepen.io/anon/pen/GWxyNj

I noticed that the preview screenshot is somehow broken in the readme, though.

**Comment by carbontwelve** [comment]
It appears that the issue was being caused due to the way I was loading Prism:

```
import Prism from 'prismjs';
import 'prism-treeview/prism-treeview.js';
Prism.highlightAll();
```

I assumed that I needed to execute `Prism.highlightAll()` to ensure that Prism highlighted as I am using ES6 import but that seems not to be necessary.

@Golmote Thank you for your help, as an aside would you be able to make this a npm package proper? I had to do the following to get it installed for my project, this sort of highlighting is quite useful for documentation pages :)

```
"scripts": {
    "install": "git clone https://github.com/Golmote/prism-treeview.git node_modules/prism-treeview"
  }
```
