### ISSUE TITLE
Nested tree structure renders with redundant file icons

### ISSUE THREAD

**Issue by ghost** [Golmote/prism-treeview#3]
```bash
> tree -F db
db/
├── 2020.10.03/
│   ├── quotes/
│   │   ├── price
│   │   ├── sym
│   │   └── time
│   └── trades/
│       ├── price
│       ├── sym
│       ├── time
│       └── vol
├── 2020.10.05/
│   ├── quotes/
│   │   ├── price
│   │   ├── sym
│   │   └── time
│   └── trades/
│       ├── price
│       ├── sym
│       ├── time
│       └── vol
└── sym
```

renders through Treeview plugin to Prism syntax highlighter as HTML

```
<pre><code class="language-treeview">db/
├── 2020.10.03/
│   ├── quotes/
│   │   ├── price
│   │   ├── sym
│   │   └── time
│   └── trades/
│       ├── price
│       ├── sym
│       ├── time
│       └── vol
├── 2020.10.05/
│   ├── quotes/
│   │   ├── price
│   │   ├── sym
│   │   └── time
│   └── trades/
│       ├── price
│       ├── sym
│       ├── time
│       └── vol
└── sym
</code></pre>
```

 and displays:

![Screenshot 2020-12-13 at 15 34 43](https://user-images.githubusercontent.com/20816256/102016447-fca4b080-3d58-11eb-9999-14c72d5542a4.png)

However the example markup from this repository displays correctly when pasted into the same context. 
Similar but less complex file trees correctly display at https://code.kx.com/q/database/.

Prism CSS and JS:
[prism.zip](https://github.com/Golmote/prism-treeview/files/5684892/prism.zip)

Workarounds eliminated:

* remove periods from folder names
* add extensions to files

**Comment by chrismullins** [comment]
I had a similar issue, and found that I needed to specify the charset in the `tree` command.  

In other words, `tree -F content` returns
```
content
├── posts/
│   ├── post-1.md
│   ├── post-2.md
│   ├── post-3.md
│   └── post-4.md
└── taggroups/
        └── blog.md
```
which would show the problem you're seeing, whereas `tree -F --charset=ascii content` returns

```
content
|-- posts/
|   |-- post-1.md
|   |-- post-2.md
|   |-- post-3.md
|   `-- post-4.md
`-- taggroups/
    `-- blog.md
```

Note the difference in the horizontal line characters.  Hope this helps!

**Comment by Golmote** [comment]
Thank you for looking into this!
