### ISSUE TITLE
Directory names starting with a (.) dot treated as dot files

### ISSUE THREAD

**Issue by randiratnayake** [Golmote/prism-treeview#5]
Current styling considers directory names starting with a (.) dot as a dot file and applies the class `dotfile`, making it appear too little odd.

**Current Behaviour**

```treeview
root/
|-- .github/
|   |-- actions/
|   |-- workflows/
|   |-- PULL_REQUEST_TEMPLATE/
|-- .gitignore
`-- README.md
```

![image](https://user-images.githubusercontent.com/25071773/183934203-a1a4aab7-d139-4e4a-af08-15570a1bf1bd.png)

**Suggestion**

Move the below code block under the else condition so only it is applied when it is not a directory.
```
if(env.content.charAt(0)==='.') {
    env.classes.push('dotfile');
}
```

**Comment by LeaVerou** [comment]
LGTM. Pull request?

**Comment by randiratnayake** [comment]
> LGTM. Pull request?

Raised #6
